DATA_PATH: '/home/sajed_hassan/thesis/MMIS/dataset/splitted'
DATASET: 'splitted'

RANDOM_SEED: 1337

MODEL_DIR: '/home/sajed_hassan/thesis/MMIS/D-Persona/models/'

INPUT_CHANNEL: 3
OUTPUT_CHANNEL: 1
TRAIN_BATCHSIZE: 12
VAL_BATCHSIZE: 1 # fixed

PRT_LOSS: False
VISUALIZE: False
TEST_SAVE: True
