DATA_PATH: '/home/sajed/thesis/MMIS/dataset/MMIS2024TASK2_train'
DATASET: 'TASK2'

RANDOM_SEED: 1337

MODEL_DIR: '/home/sajed/thesis/MMIS/D-Persona/models/'

INPUT_CHANNEL: 3
OUTPUT_CHANNEL: 1
TRAIN_BATCHSIZE: 1
VAL_BATCHSIZE: 1 # fixed

PRT_LOSS: False
VISUALIZE: False
TEST_SAVE: True
