DATA_PATH: '/Users/sajedalmorsy/Academic/Masters/thesis/D-Persona/dataset/MMIS2024TASK2_train'
DATASET: 'TASK2'

RANDOM_SEED: 1337

MODEL_DIR: '/Users/sajedalmorsy/Academic/Masters/thesis/D-Persona/D-Persona/models/'

INPUT_CHANNEL: 3
OUTPUT_CHANNEL: 1
TRAIN_BATCHSIZE: 1
VAL_BATCHSIZE: 1 # fixed

PRT_LOSS: False
VISUALIZE: False
TEST_SAVE: True
