# DATA_PATH: '/home/sajed/thesis/MMIS/dataset/GENERATED_NPC/' # 0.35 iou
# DATA_PATH: '/home/sajed/thesis/MMIS/dataset/MMIS2024TASK1'
# DATA_PATH: /home/sajed/thesis/MMIS/dataset/GENERATED_NPC_IOU_0
# DATA_PATH: '/home/sajed/thesis/MMIS/dataset/GENERATED_NPC_IOU_IMP_35/'
# DATA_PATH: '/home/sajed/thesis/MMIS/dataset/GENERATED_NPC_IOU_IMP_45/'
# DATA_PATH: '/home/sajed/thesis/MMIS/dataset/GENERATED_NPC_IOU_IMP_55/'
# DATA_PATH: '/home/sajed/thesis/MMIS/dataset/GENERATED_NPC_IOU_IMP_100/'
# DATA_PATH: '/home/sajed/thesis/MMIS/dataset/GENERATED_NPC_IOU_IMP_100_ORG_2/'
# DATA_PATH: '/home/sajed/thesis/MMIS/dataset/GENERATED_NPC_IOU_IMP_100_ORG_2_ONLY/'
# DATA_PATH: '/home/sajed/thesis/MMIS/dataset/ORG_1_ONLY_stage2_GENERATED/'
# DATA_PATH: '/home/sajed/thesis/MMIS/dataset/GENERATED_NPC_FROM_NNUNET_WITH_LEARNABLE_EMB/'
DATA_PATH: '/home/sajed/thesis/MMIS/dataset/GENERATED_NPC_FROM_NNUNET_WITH_LEARNABLE_EMB_E32_SM_ES_DS_F5_P250_(1)/'
# DATA_PATH: '/home/sajed/thesis/MMIS/dataset/GENERATED_NPC_FROM_NNUNET_WITH_LEARNABLE_3D_EMB_E32_SM_ES_DS_F5_P250_(1)'
# DATA_PATH: '/home/sajed/thesis/MMIS/dataset/GENERATED_NPC_FROM_NNUNET_WITH_LEARNABLE_EMB_E32_SM_ES_DS_F5_P250_(2)'
DATASET: 'NPC'

RANDOM_SEED: 1337

MODEL_DIR: '/home/sajed/thesis/MMIS/D-Persona/models/'

INPUT_CHANNEL: 3
OUTPUT_CHANNEL: 1
TRAIN_BATCHSIZE: 12
VAL_BATCHSIZE: 1 # fixed

PRT_LOSS: False
VISUALIZE: False
TEST_SAVE: True
