DATA_PATH: '../../dataset/'
DATASET: 'NPC'

RANDOM_SEED: 1337

MODEL_DIR: '../models/'

INPUT_CHANNEL: 3
OUTPUT_CHANNEL: 1
TRAIN_BATCHSIZE: 12
VAL_BATCHSIZE: 1 # fixed

PRT_LOSS: False
VISUALIZE: False
TEST_SAVE: True
