DATA_PATH: '../../dataset/lidc_attributes.pkl'
DATASET: 'LIDC'

RANDOM_SEED: 1337

MODEL_DIR: '../models/'

INPUT_CHANNEL: 1
OUTPUT_CHANNEL: 1
TRAIN_BATCHSIZE: 12
VAL_BATCHSIZE: 1 # fixed

PRT_LOSS: False
VISUALIZE: False
TEST_SAVE: True